#!/bin/bash

case "$1" in
    earlyshutdown)
        logger -t upssched-cmd "Trigger: earlyshutdown (power offline > 60s)"
        /usr/sbin/upsmon -c fsd
        ;;
    *)
        logger -t upssched-cmd "Unknown upssched command: $1"
        ;;
esac